Update crossbow.yml

diff --git a/.github/workflows/crossbow.yml b/.github/workflows/crossbow.yml
--- a/.github/workflows/crossbow.yml
+++ b/.github/workflows/crossbow.yml
@@ -50,7 +50,20 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.12"
-          architecture: "ARM64"  
+          architecture: "ARM64" 
+
+      - name: Install LLVM for Windows ARM64
+        shell: pwsh
+        run: |
+          Invoke-WebRequest https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.7/LLVM-21.1.7-woa64.exe -UseBasicParsing -OutFile LLVM-woa64.exe
+          $expectedHash = "b2e6090e3c6899e405f138545256dd881d93eb108e88ba10efbdb793ccbbeef6"
+          $fileHash = (Get-FileHash -Path "LLVM-woa64.exe" -Algorithm SHA256).Hash
+          if ($fileHash -ne $expectedHash) {
+              Write-Error "Checksum verification failed. The downloaded file may be corrupted or tampered with."
+              exit 1
+          }
+          Start-Process -FilePath ".\LLVM-woa64.exe" -ArgumentList "/S" -Wait
+          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
       - name: Cache vcpkg dependencies
         uses: actions/cache@v4
